-- =====================================================================
-- StarSolution — seed data
-- Mirrors src/data/site.json. Run after schema.sql.
-- =====================================================================

-- solutions
insert into public.solutions (id, slug, title, eyebrow, summary, short, icon, tone, badge, stats, points, video, sort_order) values ('sol-revenue', 'revenue-automation', 'Revenue Automation', 'Solution · +45% AOV', 'AI-optimized pricing, upsells and abandoned cart recovery running around the clock, so every visitor sees the offer most likely to convert them.', 'Pricing, upsells and cart recovery — 24/7.', 'revenue', '#3B82F6', '+45% AOV', '[["Avg order value", "+45%"], ["Carts recovered", "1 in 3"], ["Setup time", "7–14 days"]]'::jsonb, '["Dynamic upsell and bundle logic based on cart contents", "Cart recovery sequences over email, SMS and WhatsApp", "Post-purchase offers triggered automatically", "Price testing that reports back what actually converts"]'::jsonb, '{}'::jsonb, '0') on conflict (id) do nothing;
insert into public.solutions (id, slug, title, eyebrow, summary, short, icon, tone, badge, stats, points, video, sort_order) values ('sol-fulfilment', 'order-fulfillment', 'Order Fulfillment', 'Solution · 0 manual work', 'From order to delivery — fulfillment, supplier routing, tracking and customer notifications handled end to end without a spreadsheet.', 'Order to delivery, hands off.', 'package', '#38BDF8', '0 manual work', '[["Time saved", "20 hrs/week"], ["Manual steps", "0"], ["Setup time", "7–14 days"]]'::jsonb, '["Orders routed to the right supplier automatically", "Tracking numbers pushed back to the customer", "Stock synced across every sales channel", "Exceptions flagged to your team with full context"]'::jsonb, '{}'::jsonb, '1') on conflict (id) do nothing;
insert into public.solutions (id, slug, title, eyebrow, summary, short, icon, tone, badge, stats, points, video, sort_order) values ('sol-social', 'social-media-growth', 'Social Media Growth', 'Solution · 10x followers', 'Auto-posting, engagement and content scheduling for Instagram and TikTok, timed to when your audience is actually online.', 'Auto-posting for Instagram and TikTok.', 'social', '#F472B6', '10x followers', '[["Follower growth", "up to 10x"], ["Posts/week", "14+"], ["Hours saved", "12/week"]]'::jsonb, '["AI captions and hashtags matched to each post", "Publishing at peak engagement windows", "Comment and DM replies handled automatically", "Monthly reporting on reach, saves and follows"]'::jsonb, '{}'::jsonb, '2') on conflict (id) do nothing;
insert into public.solutions (id, slug, title, eyebrow, summary, short, icon, tone, badge, stats, points, video, sort_order) values ('sol-shopify', 'shopify-optimization', 'Shopify Optimization', 'Solution · +38% CVR', 'Speed, SEO and conversion work that turns more of the traffic you already pay for into buyers.', 'Speed, SEO and CRO.', 'bag', '#34D399', '+38% CVR', '[["Conversion rate", "+38%"], ["Load time", "under 2s"], ["Setup time", "10–14 days"]]'::jsonb, '["Theme and image optimization for Core Web Vitals", "Technical SEO, structured data and sitemap fixes", "Checkout and product page CRO", "Bilingual Arabic / English store setup"]'::jsonb, '{}'::jsonb, '3') on conflict (id) do nothing;
insert into public.solutions (id, slug, title, eyebrow, summary, short, icon, tone, badge, stats, points, video, sort_order) values ('sol-ads', 'ai-smart-ads', 'AI Smart Ads', 'Solution · 4.2x ROAS', 'Machine learning manages your Meta and Google campaigns — budget moves to what performs, daily, without you watching it.', 'ML-managed Meta and Google ads.', 'target', '#FBBF24', '4.2x ROAS', '[["Average ROAS", "4.2x"], ["Ad spend", "−35%"], ["Reporting", "Daily"]]'::jsonb, '["Budget reallocated to the best performing ad sets", "Creative testing on a fixed weekly cycle", "Audience building from your own store data", "Full funnel tracking from click to delivered order"]'::jsonb, '{}'::jsonb, '4') on conflict (id) do nothing;
insert into public.solutions (id, slug, title, eyebrow, summary, short, icon, tone, badge, stats, points, video, sort_order) values ('sol-support', 'ai-customer-support', 'AI Customer Support', 'Solution · 80% automated', 'A chatbot that answers 80% of questions instantly on WhatsApp and your website, and hands the rest to your team with the full conversation attached.', 'Instant replies on WhatsApp and your site.', 'bot', '#7C6CFF', '80% automated', '[["Questions handled", "80%"], ["First reply", "under 2s"], ["Languages", "Arabic + English"]]'::jsonb, '["Trained on your products, policies and order data", "Live order status lookups inside the chat", "Escalation to a human with full context", "Available every hour of every day"]'::jsonb, '{}'::jsonb, '5') on conflict (id) do nothing;

-- goals
insert into public.goals (id, slug, title, eyebrow, summary, short, icon, tone, metric, "metricLabel", stats, points, video, sort_order) values ('goal-revenue', 'increase-revenue', 'Increase revenue', 'Goal', 'Lift what each customer spends without buying more traffic. Smart upsells, AI pricing and cart recovery do the work.', 'Upsells, AI pricing, cart recovery.', 'revenue', '#3B82F6', '+45%', 'average order value', '[["Avg order value", "+45%"], ["Revenue growth", "+132%"], ["Typical payback", "Month 1"]]'::jsonb, '["Start with a free audit of your current funnel", "We build upsell and recovery flows around your catalog", "You keep the system whether or not you continue with us"]'::jsonb, '{}'::jsonb, '0') on conflict (id) do nothing;
insert into public.goals (id, slug, title, eyebrow, summary, short, icon, tone, metric, "metricLabel", stats, points, video, sort_order) values ('goal-ops', 'automate-operations', 'Automate operations', 'Goal', 'Orders, fulfillment, tracking and supplier updates run end to end so your team stops copying data between tabs.', 'Orders and fulfillment on autopilot.', 'package', '#7C6CFF', '20hrs', 'saved every week', '[["Hours saved", "20/week"], ["Manual steps", "0"], ["Go live", "Under 14 days"]]'::jsonb, '["We map your current workflow before changing anything", "Automations plug into the tools you already use", "Everything is monitored, with alerts when something needs a human"]'::jsonb, '{}'::jsonb, '1') on conflict (id) do nothing;
insert into public.goals (id, slug, title, eyebrow, summary, short, icon, tone, metric, "metricLabel", stats, points, video, sort_order) values ('goal-support', 'improve-customer-support', 'Improve customer support', 'Goal', 'An AI agent replies on WhatsApp and on your store in seconds, day and night, in Arabic and English.', 'AI replies in seconds, day and night.', 'headset', '#38BDF8', '80%', 'of questions handled', '[["Handled by AI", "80%"], ["Response time", "under 2s"], ["Team time saved", "4 hrs/day"]]'::jsonb, '["Answers product, shipping and order status questions", "Escalates anything sensitive to your team", "Learns from every conversation your team resolves"]'::jsonb, '{}'::jsonb, '2') on conflict (id) do nothing;
insert into public.goals (id, slug, title, eyebrow, summary, short, icon, tone, metric, "metricLabel", stats, points, video, sort_order) values ('goal-decisions', 'make-better-decisions', 'Make better decisions', 'Goal', 'One live dashboard for revenue, orders, visitors and ROAS, so you stop guessing which channel is actually working.', 'One live dashboard for everything.', 'chart', '#34D399', '4.2x', 'ROAS on managed ads', '[["Managed ROAS", "4.2x"], ["Reporting", "Live"], ["Setup time", "5–7 days"]]'::jsonb, '["Revenue, orders and traffic in a single view", "Channel level ROAS across Meta, Google and TikTok", "Weekly summary delivered to WhatsApp or email"]'::jsonb, '{}'::jsonb, '3') on conflict (id) do nothing;

-- case_studies
insert into public.case_studies (id, slug, title, eyebrow, summary, type, kpi, "kpiUnit", "kpiLabel", before, after, delta, period, c1, c2, stats, points, video, sort_order) values ('case-cairo', 'ecommerce-store-cairo', '20 to 85 orders a day', 'Case study · E-commerce store, Cairo', 'A Cairo e-commerce store moved from manual order handling to a fully automated pipeline in six weeks.', 'E-commerce store · Cairo', '85', '/day', 'Orders after automation', '20 orders/day', '85 orders/day', '+325%', 'in 6 weeks', '#3B82F6', '#7C6CFF', '[["Before", "20 orders/day"], ["After", "85 orders/day"], ["Change", "+325%"]]'::jsonb, '["Order routing, fulfillment and tracking automated end to end", "Abandoned cart recovery added across email and WhatsApp", "Owner: \"Everything runs automatically while I sleep.\""]'::jsonb, '{}'::jsonb, '0') on conflict (id) do nothing;
insert into public.case_studies (id, slug, title, eyebrow, summary, type, kpi, "kpiUnit", "kpiLabel", before, after, delta, period, c1, c2, stats, points, video, sort_order) values ('case-beauty', 'beauty-brand', '2K to 18K followers', 'Case study · Beauty brand', 'Content scheduling and engagement automation grew an Instagram audience 9x in three months.', 'Beauty brand', '18K', ' followers', 'Instagram after 3 months', '2K followers', '18K followers', '+800%', 'in 3 months', '#F472B6', '#7C6CFF', '[["Before", "2K followers"], ["After", "18K followers"], ["Change", "+800%"]]'::jsonb, '["AI captions and hashtags on a fixed posting cadence", "Publishing timed to peak engagement windows", "Founder: \"The AI posts content better than I ever did.\""]'::jsonb, '{}'::jsonb, '1') on conflict (id) do nothing;
insert into public.case_studies (id, slug, title, eyebrow, summary, type, kpi, "kpiUnit", "kpiLabel", before, after, delta, period, c1, c2, stats, points, video, sort_order) values ('case-shopify', 'shopify-store', '1.8% to 4.2% conversion', 'Case study · Shopify store', 'Store speed, SEO and checkout work more than doubled conversion while ad spend came down.', 'Shopify store', '4.2', '% CVR', 'Shopify conversion rate', '1.8% CVR', '4.2% CVR', '+133%', 'and 35% less ad spend', '#34D399', '#3B82F6', '[["Before", "1.8% CVR"], ["After", "4.2% CVR"], ["Ad spend", "−35%"]]'::jsonb, '["Theme and image optimization for Core Web Vitals", "Product page and checkout CRO", "Owner: \"Ad spend dropped 35%. Genuinely good.\""]'::jsonb, '{}'::jsonb, '2') on conflict (id) do nothing;
insert into public.case_studies (id, slug, title, eyebrow, summary, type, kpi, "kpiUnit", "kpiLabel", before, after, delta, period, c1, c2, stats, points, video, sort_order) values ('case-electronics', 'electronics-store', '1.8x to 4.5x ROAS', 'Case study · Electronics store', 'AI managed budget allocation across Meta and Google paid for the whole engagement inside the first month.', 'Electronics store', '4.5', 'x ROAS', 'Meta and Google ads', '1.8x ROAS', '4.5x ROAS', '+150%', 'paid back in month one', '#FBBF24', '#F472B6', '[["Before", "1.8x ROAS"], ["After", "4.5x ROAS"], ["Change", "+150%"]]'::jsonb, '["Daily budget reallocation to the best performing sets", "Weekly creative testing cycle", "Owner: \"It paid for everything in the first month.\""]'::jsonb, '{}'::jsonb, '3') on conflict (id) do nothing;
insert into public.case_studies (id, slug, title, eyebrow, summary, type, kpi, "kpiUnit", "kpiLabel", before, after, delta, period, c1, c2, stats, points, video, sort_order) values ('case-decor', 'home-decor-brand', '+280% revenue in 4 months', 'Case study · Home decor brand', 'A live dashboard replaced guesswork, and revenue followed.', 'Home decor brand', '+280', '%', 'Revenue in 4 months', 'No live data', 'Live dashboard', '+280%', 'revenue in 4 months', '#7C6CFF', '#38BDF8', '[["Revenue", "+280%"], ["Timeframe", "4 months"], ["Reporting", "Live"]]'::jsonb, '["Revenue, orders and traffic unified in one view", "Channel level ROAS across every paid source", "Founder: \"I feel in control for the first time.\""]'::jsonb, '{}'::jsonb, '4') on conflict (id) do nothing;

-- systems
insert into public.systems (id, slug, title, eyebrow, summary, short, tag, stats, points, video, sort_order) values ('sys-accounting', 'accounting-system', 'Accounting System', 'Custom system · SaaS', 'Invoicing, expense tracking, financial reports and multi-user access, built for small and medium businesses.', 'Invoicing, expenses and reports.', 'SaaS system', '[["Users", "Multi-user"], ["Reports", "Automated"], ["Demo", "On request"]]'::jsonb, '["Invoice generation and payment tracking", "Expense categories and receipt capture", "Monthly and quarterly financial reports", "Role based access for accountants and owners"]'::jsonb, '{}'::jsonb, '0') on conflict (id) do nothing;
insert into public.systems (id, slug, title, eyebrow, summary, short, tag, stats, points, video, sort_order) values ('sys-seo', 'seo-forge', 'SEO Forge', 'Custom system · AI + SEO', 'Keyword research, content generation, rank tracking and site audits, powered by AI.', 'Keywords, content and rank tracking.', 'AI + SEO', '[["Languages", "Arabic + English"], ["Tracking", "Daily"], ["Demo", "On request"]]'::jsonb, '["Keyword research with local search intent", "AI drafted content briefs and copy", "Daily rank tracking by keyword and page", "Technical site audits with prioritized fixes"]'::jsonb, '{}'::jsonb, '1') on conflict (id) do nothing;
insert into public.systems (id, slug, title, eyebrow, summary, short, tag, stats, points, video, sort_order) values ('sys-courier', 'courier-system', 'Courier System', 'Custom system · Logistics', 'Order dispatch, driver tracking, real-time status and automated customer notifications.', 'Dispatch, tracking and notifications.', 'Logistics', '[["Tracking", "Real time"], ["Notifications", "Automated"], ["Demo", "On request"]]'::jsonb, '["Dispatch orders to available drivers automatically", "Live map tracking for every delivery", "Status updates pushed to the customer", "Delivery performance reporting by driver and zone"]'::jsonb, '{}'::jsonb, '2') on conflict (id) do nothing;
insert into public.systems (id, slug, title, eyebrow, summary, short, tag, stats, points, video, sort_order) values ('sys-trading', 'trading-system', 'Trading System', 'Custom system · Fintech', 'Live market data, portfolio tracking, buy and sell signals and automated execution.', 'Live data, signals and execution.', 'Fintech', '[["Data", "Live"], ["Execution", "Automated"], ["Demo", "On request"]]'::jsonb, '["Live market data feeds", "Portfolio performance tracking", "Signal generation from configurable rules", "Automated execution with manual override"]'::jsonb, '{}'::jsonb, '3') on conflict (id) do nothing;
insert into public.systems (id, slug, title, eyebrow, summary, short, tag, stats, points, video, sort_order) values ('sys-analytics', 'google-analytics-system', 'Google Analytics System', 'Custom system · Analytics', 'GA4 traffic insights, conversion funnels, real-time reports and automated alerts.', 'Traffic, funnels and alerts.', 'Analytics', '[["Platform", "GA4"], ["Alerts", "Automated"], ["Demo", "On request"]]'::jsonb, '["Traffic and acquisition breakdowns", "Conversion funnel analysis", "Real-time reporting dashboards", "Alerts when a metric moves outside its range"]'::jsonb, '{}'::jsonb, '4') on conflict (id) do nothing;

-- automations
insert into public.automations (id, slug, title, eyebrow, summary, stats, points, video, sort_order) values ('auto-stripe', 'stripe-payment-automation', 'Stripe payment automation', 'Automation', 'Payments, receipts, refunds and reconciliation handled without anyone opening the dashboard.', '[["Setup", "3–5 days"], ["Manual work", "0"]]'::jsonb, '["Automatic receipts and invoices", "Failed payment retry sequences", "Refunds synced back to your store", "Daily reconciliation report"]'::jsonb, '{}'::jsonb, '0') on conflict (id) do nothing;
insert into public.automations (id, slug, title, eyebrow, summary, stats, points, video, sort_order) values ('auto-whatsapp', 'whatsapp-ai-system', 'WhatsApp AI system', 'Automation', 'An AI agent on WhatsApp Business handling orders, questions and confirmations in Arabic and English.', '[["Reply time", "under 2s"], ["Automated", "80%"]]'::jsonb, '["Order confirmation and rescheduling flows", "Live order status lookups", "Escalation to your team with full context", "Broadcast campaigns to opted-in customers"]'::jsonb, '{}'::jsonb, '1') on conflict (id) do nothing;
insert into public.automations (id, slug, title, eyebrow, summary, stats, points, video, sort_order) values ('auto-courier', 'courier-and-delivery-system', 'Courier and delivery system', 'Automation', 'Connects your store to your courier so dispatch, tracking and notifications happen on their own.', '[["Setup", "5–7 days"], ["Tracking", "Automatic"]]'::jsonb, '["Shipments created the moment an order is paid", "Tracking numbers returned to the customer", "Delivery exceptions flagged to your team"]'::jsonb, '{}'::jsonb, '2') on conflict (id) do nothing;
insert into public.automations (id, slug, title, eyebrow, summary, stats, points, video, sort_order) values ('auto-youtube', 'youtube-ai-generator', 'YouTube AI generator', 'Automation', 'Turns your product catalog and blog content into scripted, scheduled video output.', '[["Output", "Weekly"], ["Input", "Your catalog"]]'::jsonb, '["Scripts generated from existing product content", "Titles, descriptions and tags optimized for search", "Scheduled publishing on a fixed cadence"]'::jsonb, '{}'::jsonb, '3') on conflict (id) do nothing;
insert into public.automations (id, slug, title, eyebrow, summary, stats, points, video, sort_order) values ('auto-chatbot', 'ecommerce-chatbot', 'E-commerce chatbot', 'Automation', 'An on-site assistant that answers product questions and guides visitors to checkout.', '[["Handled", "80%"], ["Languages", "Arabic + English"]]'::jsonb, '["Trained on your catalog and policies", "Product recommendations inside the chat", "Handover to a human when needed"]'::jsonb, '{}'::jsonb, '4') on conflict (id) do nothing;
insert into public.automations (id, slug, title, eyebrow, summary, stats, points, video, sort_order) values ('auto-custom', 'custom-automations', 'Custom automations', 'Automation', 'If it happens more than twice a week and follows rules, it can be automated. Tell us the workflow.', '[["Scope", "Anything repeatable"], ["Start", "Free audit"]]'::jsonb, '["We map the workflow before building anything", "Built on the tools you already pay for", "Documented and handed over, not locked in"]'::jsonb, '{}'::jsonb, '5') on conflict (id) do nothing;

-- team
insert into public.team (id, slug, title, eyebrow, summary, role, initials, tone, points, sort_order) values ('team-heba', 'heba-hesham', 'Heba Hesham', 'Team', 'Senior web developer. Builds and maintains the Shopify themes, custom storefronts and client systems.', 'Senior web developer', 'HH', '#3B82F6', '["Shopify OS 2.0 theme development", "Custom storefront and system builds", "Performance and SEO implementation"]'::jsonb, '0') on conflict (id) do nothing;
insert into public.team (id, slug, title, eyebrow, summary, role, initials, tone, points, sort_order) values ('team-hams', 'hams', 'Hams', 'Team', 'Software engineer. Works across the automation backends and integrations.', 'Software engineer', 'HA', '#7C6CFF', '["Automation workflows and API integrations", "Backend services and data pipelines"]'::jsonb, '1') on conflict (id) do nothing;
insert into public.team (id, slug, title, eyebrow, summary, role, initials, tone, points, sort_order) values ('team-mera', 'mera', 'Mera', 'Team', 'Software engineer. Focused on dashboards, reporting and client-facing systems.', 'Software engineer', 'ME', '#38BDF8', '["Dashboard and reporting interfaces", "System integrations and QA"]'::jsonb, '2') on conflict (id) do nothing;
insert into public.team (id, slug, title, eyebrow, summary, role, initials, tone, points, sort_order) values ('team-ganna', 'ganna', 'Ganna', 'Team', 'Content creator. Produces the copy and creative that the automations publish.', 'Content creator', 'GA', '#34D399', '["Product and campaign copy", "Creative direction for social output"]'::jsonb, '3') on conflict (id) do nothing;
insert into public.team (id, slug, title, eyebrow, summary, role, initials, tone, points, sort_order) values ('team-ebtsam', 'ebtsam', 'Ebtsam', 'Team', 'Social media creator. Runs the content calendars and engagement for client accounts.', 'Social media creator', 'EB', '#F472B6', '["Content calendars for Instagram and TikTok", "Engagement and community management"]'::jsonb, '4') on conflict (id) do nothing;
insert into public.team (id, slug, title, eyebrow, summary, role, initials, tone, points, sort_order) values ('team-amira', 'amira', 'Amira', 'Team', 'Customer support. First point of contact for clients, in Arabic and English.', 'Customer support', 'AM', '#FBBF24', '["Client onboarding and day to day support", "Escalation handling"]'::jsonb, '5') on conflict (id) do nothing;
insert into public.team (id, slug, title, eyebrow, summary, role, initials, tone, points, sort_order) values ('team-jumana', 'jumana', 'Jumana', 'Team', 'Customer support. Handles account questions and coordinates with the build team.', 'Customer support', 'JU', '#3B82F6', '["Account and billing questions", "Coordination between clients and engineers"]'::jsonb, '6') on conflict (id) do nothing;

-- testimonials
insert into public.testimonials (id, name, role, quote, initials, tone, sort_order) values ('t-omar', 'Omar Hassan', 'E-commerce owner, Cairo', 'Orders went from 20/day to 85/day in 6 weeks. Everything runs automatically while I sleep.', 'OH', '#3B82F6', '0') on conflict (id) do nothing;
insert into public.testimonials (id, name, role, quote, initials, tone, sort_order) values ('t-layla', 'Layla Mohammed', 'Beauty brand founder', 'Instagram went from 2K to 18K followers in 3 months. The AI posts content better than I ever did.', 'LM', '#F472B6', '1') on conflict (id) do nothing;
insert into public.testimonials (id, name, role, quote, initials, tone, sort_order) values ('t-ahmed', 'Ahmed Farouk', 'Shopify store owner', 'Shopify conversion rate jumped from 1.8% to 4.2%. Ad spend dropped 35%. Genuinely good.', 'AF', '#34D399', '2') on conflict (id) do nothing;
insert into public.testimonials (id, name, role, quote, initials, tone, sort_order) values ('t-nadia', 'Nadia El-Sayed', 'Fashion brand, Dubai', 'The chatbot handles 80% of my customer queries. I used to spend 4 hours a day on WhatsApp.', 'NE', '#7C6CFF', '3') on conflict (id) do nothing;
insert into public.testimonials (id, name, role, quote, initials, tone, sort_order) values ('t-karim', 'Karim Mansour', 'Electronics store', 'ROAS went from 1.8x to 4.5x. The AI ad optimization paid for everything in the first month.', 'KM', '#FBBF24', '4') on conflict (id) do nothing;
insert into public.testimonials (id, name, role, quote, initials, tone, sort_order) values ('t-sara', 'Sara Al-Rashid', 'Home decor brand', 'Revenue up 280% in 4 months. I feel in control for the first time with the live dashboard.', 'SR', '#38BDF8', '5') on conflict (id) do nothing;

-- projects
insert into public.projects (id, slug, title, badge, short, summary, url, accent, theme, points, sort_order) values ('p-montre', 'montre-co', 'Montre Co.', 'E-commerce', 'Shopify build, custom UI and checkout.', 'A premium watch store rebuilt on Shopify with a custom theme, redesigned product pages and a streamlined checkout.', 'https://montre-co.com/', '#3B82F6', 'montre', '["Custom Shopify OS 2.0 theme", "Product and collection page design", "Checkout and cart flow rebuilt", "Performance and SEO pass"]'::jsonb, '0') on conflict (id) do nothing;
insert into public.projects (id, slug, title, badge, short, summary, url, accent, theme, points, sort_order) values ('p-beauty', 'beauty-bareg', 'Beauty Bareg', 'Beauty & fashion', 'Store design, catalog and mobile-first UX.', 'A luxury beauty and fashion storefront with a full catalog build, social integration and a mobile-first experience.', 'https://beauty-bareg.net/', '#7C6CFF', 'beauty', '["Full store design and build", "Product catalog and merchandising", "Social and campaign integration", "Mobile-first experience"]'::jsonb, '1') on conflict (id) do nothing;
